CREATE TABLE SHIPWRECK(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
	DESCRIPTION VARCHAR(2000),
	CONDITION VARCHAR(255),
	DEPTH INT,
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE,
	YEAR_DISCOVERED INT
);
CREATE TABLE `SHIPWRECK` (
	`ID` int NOT NULL,
	`NAME` varchar(255) NOT NULL,
	`DESCRIPTION` varchar(2000) NOT NULL,
	`CONDITION` varchar(255) NOT NULL,
	`DEPTH` int NOT NULL,
	`LATITUDE` double NOT NULL,
	`LONGITUDE` double NOT NULL,
	`YEAR_DISCOVERED` int NOT NULL,
	PRIMARY KEY (`ID`)
);